services:
  tetanus:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/wjdp/tetanus
    container_name: tetanus
    user: "1000:1000"
    volumes:
      - ./data:/app/data
    ports:
      - 3000:3000
    environment:
      - TZ=${TZ:-UTC}
