import { readFileSync, writeFileSync } from "node:fs";

const migrationsDir = new URL(
  "../../server/database/migrations/",
  import.meta.url,
);
const outputFile = new URL("migrations.ts", import.meta.url);

type JournalEntry = { idx: number; tag: string };

const journal = JSON.parse(
  readFileSync(new URL("meta/_journal.json", migrationsDir), "utf8"),
) as { entries: JournalEntry[] };

const migrations = Object.fromEntries(
  journal.entries.map((entry) => [
    `m${entry.idx.toString().padStart(4, "0")}`,
    readFileSync(new URL(`${entry.tag}.sql`, migrationsDir), "utf8"),
  ]),
);

writeFileSync(
  outputFile,
  `// Generated by bundleMigrations.ts from server/database/migrations; do not edit.
export default ${JSON.stringify({ journal, migrations }, null, 2)};
`,
);

console.log(
  `Bundled ${journal.entries.length} migrations into ${outputFile.pathname}`,
);
