import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const journalFile = new URL(
  "../../server/database/migrations/meta/_journal.json",
  import.meta.url,
);
const outputFile = new URL("schemaBundle.ts", import.meta.url);

const journal = JSON.parse(readFileSync(journalFile, "utf8")) as {
  entries: { tag: string }[];
};

const sql = execFileSync("drizzle-kit", ["export"], {
  cwd: new URL("../..", import.meta.url),
  encoding: "utf8",
  stdio: ["ignore", "pipe", "inherit"],
});
if (!sql.includes("CREATE TABLE")) {
  throw new Error(`drizzle-kit export produced no schema:\n${sql}`);
}

const bundle = {
  sql,
  hash: createHash("sha256").update(sql).digest("hex").slice(0, 12),
  latestMigration: journal.entries.at(-1)?.tag ?? null,
};

writeFileSync(
  outputFile,
  `// Generated by bundleSchema.ts from drizzle-kit export; do not edit.
export default ${JSON.stringify(bundle, null, 2)};
`,
);

console.log(`Bundled schema ${bundle.hash} into ${outputFile.pathname}`);
