export const vdev = (
  name: string,
  type: string,
  children: object[] = [],
  extra = {},
) => ({
  id: name.length,
  guid: `guid-${name}`,
  parentId: null,
  name,
  type,
  role: "normal",
  state: "ONLINE",
  spareState: null,
  readErrors: 0,
  writeErrors: 0,
  checksumErrors: 0,
  slowIos: 0,
  path: null,
  devid: null,
  physPath: null,
  allocBytes: null,
  sizeBytes: null,
  frag: null,
  present: true,
  lastSeenAt: "2026-09-28T10:00:00.000Z",
  disk: null,
  children,
  ...extra,
});

export const tank = {
  id: 7,
  guid: "4620770592528249368",
  name: "tank",
  path: "/zfs/nas1/tank",
  archivedAt: null as string | null,
  archiveNote: "",
  state: "ONLINE",
  displayState: "ONLINE",
  status: "Some supported features are not enabled.",
  action: null,
  msgid: null,
  moreinfo: null,
  health: "ONLINE",
  errors: 0,
  damagedFiles: null,
  damagedFilesError: null,
  sizeBytes: 36e12,
  allocBytes: 18e12,
  freeBytes: 18e12,
  frag: 3,
  cap: 50,
  dedup: 1,
  scan: {
    function: "SCRUB",
    state: "FINISHED",
    startTime: 1789255441,
    endTime: 1789325257,
    examined: 100,
    toExamine: 100,
    errors: 0,
  },
  scanProgressAt: null,
  lastScrub: null,
  removal: null,
  config: null,
  resolvedConfig: { scrubIntervalDays: 35, slowIoThreshold: 10 },
  firstSeenAt: "2026-09-01T00:00:00.000Z",
  lastSeenAt: "2026-09-28T10:00:00.000Z",
  host: { id: 1, name: "nas1", displayName: null },
  vdevs: vdev("tank", "root", [
    vdev("raidz1-0", "raidz1", [
      vdev("/dev/disk/by-vdev/K1-part1", "disk", [], {
        checksumErrors: 2,
        disk: { id: 3, alias: "K1", state: "in-use", latestStatus: "passed" },
      }),
      vdev("/dev/disk/by-vdev/K2-part1", "disk", [], {
        id: 99,
        disk: { id: 4, alias: "K2", state: "in-use", latestStatus: "unknown" },
      }),
    ]),
  ]),
  readings: [],
  usable: {
    used: 2 ** 43,
    available: 3 * 2 ** 43,
    at: "2026-09-28T10:00:00.000Z",
  },
  diary: [],
  history: [
    {
      id: 1,
      hostId: 1,
      poolId: null,
      at: "2026-09-20T02:00:00.000Z",
      internal: false,
      text: "zpool scrub tank",
    },
  ],
  historyScope: "host",
  events: [],
  datasetCount: 2,
  snapshotCount: 0,
};
